language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - laura.canelada.velasco@upm.es
script:
  #Test unitario y de integracion con cobertura
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  #SONARCLOUD
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=lau-cv -Dsonar.login=$SONAR -Dsonar.projectKey=laucv_apaw-ep-laura-canelada

#Deploy https://apaw-ep-xxx.herokuapp.com
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master

